name: Action for testing OSS uplload

on:
  workflow_dispatch:

permissions:
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure Aliyun Credentials
        uses: aliyun/configure-aliyun-credentials-action@v1
        with:
          role-to-assume: 'acs:ram::5352290963333981:role/githubdev'
          oidc-provider-arn: 'acs:ram::5352290963333981:oidc-provider/GitHub'
          role-session-name: 'github-action-session'
          role-session-expiration: 1800
          audience: 'github-actions'